<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN" sourcelanguage="en_US">
<context>
    <name>MainWindow</name>
    <message>
        <source>title_this_app</source>
        <translation>C++类自动生成工具</translation>
    </message>
	
	<message>
        <source>menu_theme</source>
        <translation>主题</translation>
    </message>
	<message>
        <source>menu_language</source>
        <translation>语言</translation>
    </message>
	<message>
        <source>menu_chinese</source>
        <translation>中文</translation>
    </message>
	<message>
        <source>menu_english</source>
        <translation>English</translation>
    </message>
	<message>
        <source>menu_feedback</source>
        <translation>反馈</translation>
    </message>
	<message>
        <source>menu_about</source>
        <translation>关于</translation>
    </message>
	
	<message>
        <source>title_exit</source>
        <translation>提示</translation>
    </message>
	<message>
        <source>tip_exit_message</source>
        <translation>确认要退出吗？</translation>
    </message>
	
	<message>
        <source>title_msg_yes</source>
        <translation>确认</translation>
    </message>
	<message>
        <source>title_msg_no</source>
        <translation>取消</translation>
    </message>
    
    <message>
        <source>label_class_name</source>
        <translation>类名:</translation>
    </message>
    <message>
        <source>label_file_name</source>
        <translation>文件名:</translation>
    </message>
    <message>
        <source>btn_add_func</source>
        <translation>增加函数</translation>
    </message>
    <message>
        <source>btn_del_func</source>
        <translation>减少函数</translation>
    </message>
    <message>
        <source>btn_gen_file</source>
        <translation>生成文件</translation>
    </message>
    <message>
        <source>label_return_value</source>
        <translation>返回值:</translation>
    </message>
    <message>
        <source>label_func_name</source>
        <translation>函数名:</translation>
    </message>
    <message>
        <source>label_input_param</source>
        <translation>入参:</translation>
    </message>
    <message>
        <source>column_return_value</source>
        <translation>返回值</translation>
    </message>
    <message>
        <source>column_func_name</source>
        <translation>函数名</translation>
    </message>
    <message>
        <source>column_input_param</source>
        <translation>入参[0...n]</translation>
    </message>
</context>
<context>
    <name>ThemeWindow</name>
	<message>
        <source>title_this_window</source>
        <translation>主题</translation>
    </message>
	
	<message>
        <source>info_default_theme</source>
        <translation>默认主题</translation>
    </message>
</context>
<context>
    <name>FeedbackWindow</name>
	<message>
        <source>title_this_window</source>
        <translation>反馈</translation>
    </message>
	
	<message>
        <source>info_qq</source>
        <translation>QQ群: 906772910</translation>
    </message>
	<message>
        <source>info_email</source>
        <translation>Email: iounce@foxmail.com</translation>
    </message>
</context>
<context>
    <name>AboutWindow</name>
	<message>
        <source>title_this_window</source>
        <translation>关于</translation>
    </message>
	<message>
        <source>title_this_app</source>
        <translation>PySideFrameless</translation>
    </message>
</context>
<context>
    <name>MessageWindow</name>
	<message>
        <source>title_this_window</source>
        <translation>提示</translation>
    </message>
	<message>
        <source>title_ok</source>
        <translation>确定</translation>
    </message>
	<message>
        <source>title_cancel</source>
        <translation>取消</translation>
    </message>
</context>
</TS>
